import type { Appointment } from "./types";

/**
 * Seed data for the local repository (§16 — demo persistence). Used only
 * the first time a browser opens the workspace; after that, the
 * repository reads whatever is in localStorage, including edits.
 */
export const demoAppointments: Appointment[] = [
  {
    id: "1",
    client: "Anna Müller",
    service: "Haircut",
    staff: "Elena",
    resourceId: null,
    date: "2026-09-22",
    time: "09:00",
    durationMinutes: 45,
    price: 55,
    currency: "EUR",
    notes: "",
    visibility: "normal",
    financialBucket: "main",
    status: "confirmed",
    paid: true,
    seriesId: null,
    recurrence: null,
  },
  {
    id: "2",
    client: "Jonas Schmidt",
    service: "Consultation",
    staff: "Elena",
    resourceId: null,
    date: "2026-09-22",
    time: "10:30",
    durationMinutes: 30,
    price: 40,
    currency: "EUR",
    notes: "",
    visibility: "normal",
    financialBucket: "main",
    status: "pending",
    paid: false,
    seriesId: null,
    recurrence: null,
  },
  {
    id: "3",
    client: "Example Client",
    service: "Consultation",
    staff: "You",
    resourceId: null,
    date: "2026-09-22",
    time: "14:00",
    durationMinutes: 60,
    price: 150,
    currency: "EUR",
    notes: "",
    visibility: "ownerOnly",
    financialBucket: "private",
    status: "confirmed",
    paid: true,
    seriesId: null,
    recurrence: null,
  },
  {
    id: "4",
    client: "Laura Fischer",
    service: "Deep cleaning",
    staff: "Marco",
    resourceId: "res-van",
    date: "2026-09-22",
    time: "16:00",
    durationMinutes: 90,
    price: 120,
    currency: "EUR",
    notes: "",
    visibility: "normal",
    financialBucket: "main",
    status: "confirmed",
    paid: false,
    seriesId: null,
    recurrence: null,
  },
  {
    id: "5",
    client: "Mia Weber",
    service: "Website maintenance",
    staff: "You",
    resourceId: null,
    date: "2026-09-23",
    time: "11:00",
    durationMinutes: 60,
    price: 180,
    currency: "EUR",
    notes: "",
    visibility: "normal",
    financialBucket: "main",
    status: "pending",
    paid: false,
    seriesId: null,
    recurrence: null,
  },
  {
    id: "6",
    client: "Anna Müller",
    service: "Color",
    staff: "Elena",
    resourceId: "res-room-1",
    date: "2026-09-24",
    time: "13:30",
    durationMinutes: 90,
    price: 95,
    currency: "EUR",
    notes: "",
    visibility: "normal",
    financialBucket: "main",
    status: "confirmed",
    paid: false,
    seriesId: null,
    recurrence: null,
  },
];
