import type { WorkspaceConfig } from "../types";
import type { ServiceDefinition } from "@/features/services/types";
import type { StaffMember } from "@/features/staff/types";
import type { ResourceDefinition } from "@/features/resources/types";
import type { ClientRecord } from "@/features/clients/types";
import type { Appointment } from "@/features/appointments/types";

const services: ServiceDefinition[] = [
  {
    id: "svc-regular-cleaning",
    name: "Regular cleaning",
    translations: {
      en: "Regular cleaning",
      de: "Regelmäßige Reinigung",
      uk: "Звичайне прибирання",
      ru: "Обычная уборка",
    },
    durationMinutes: 90,
    price: 80,
    currency: "EUR",
    bufferBeforeMinutes: 0,
    bufferAfterMinutes: 15,
    allowedStaffIds: [],
    requiredResourceType: null,
  },
  {
    id: "svc-deep-cleaning",
    name: "Deep cleaning",
    translations: {
      en: "Deep cleaning",
      de: "Grundreinigung",
      uk: "Генеральне прибирання",
      ru: "Генеральная уборка",
    },
    durationMinutes: 180,
    price: 180,
    currency: "EUR",
    bufferBeforeMinutes: 0,
    bufferAfterMinutes: 30,
    allowedStaffIds: [],
    requiredResourceType: "equipment",
  },
  {
    id: "svc-windows",
    name: "Windows",
    translations: { en: "Windows", de: "Fenster", uk: "Миття вікон", ru: "Мытьё окон" },
    durationMinutes: 60,
    price: 50,
    currency: "EUR",
    bufferBeforeMinutes: 0,
    bufferAfterMinutes: 10,
    allowedStaffIds: [],
    requiredResourceType: null,
  },
];

const staff: StaffMember[] = [
  { id: "staff-julia", name: "Julia", colorToken: "--color-accent-mint" },
  { id: "staff-tom", name: "Tom", colorToken: "--color-accent-blue" },
  { id: "staff-you", name: "You", colorToken: "--color-accent-lavender" },
];

const resources: ResourceDefinition[] = [
  {
    id: "res-vacuum",
    name: "Industrial vacuum",
    type: "equipment",
    translations: {
      de: "Industriesauger",
      en: "Industrial vacuum",
      uk: "Промисловий пилосос",
      ru: "Промышленный пылесос",
    },
  },
  {
    id: "res-steamer",
    name: "Steam cleaner",
    type: "equipment",
    translations: {
      de: "Dampfreiniger",
      en: "Steam cleaner",
      uk: "Пароочисник",
      ru: "Пароочиститель",
    },
  },
  {
    id: "res-equipment-set",
    name: "Equipment set 1",
    type: "equipment",
    translations: {
      de: "Ausrüstungsset 1",
      en: "Equipment set 1",
      uk: "Комплект обладнання 1",
      ru: "Комплект оборудования 1",
    },
  },
  {
    id: "res-vehicle",
    name: "Vehicle 1",
    type: "vehicle",
    translations: { de: "Fahrzeug 1", en: "Vehicle 1", uk: "Автомобіль 1", ru: "Автомобиль 1" },
  },
];

const clients: ClientRecord[] = [
  {
    id: "property-fischer",
    name: "Fischer Residence",
    email: "laura.fischer@example.com",
    phone: "+49 176 9988 7766",
    tags: ["vip"],
    lastVisit: "2026-09-15",
    upcoming: [{ date: "2026-09-22", time: "16:00", service: "Deep cleaning" }],
    history: [
      { date: "2026-09-15", service: "Regular cleaning", price: 80 },
      { date: "2026-09-01", service: "Regular cleaning", price: 80 },
    ],
    notes: "Has a dog — leave the back door closed.",
    customFields: [
      { label: "Address", value: "Lindenstraße 14, 10969 Berlin" },
      { label: "Property size", value: "95 m²" },
      { label: "Rooms", value: "4" },
      { label: "Access instructions", value: "Key box code 4471. Dog on premises, no need to let out." },
    ],
  },
  {
    id: "property-weber-office",
    name: "Weber & Co. Office",
    email: "office@weberco.example",
    phone: "+49 30 4455 6677",
    tags: [],
    lastVisit: "2026-09-10",
    upcoming: [],
    history: [{ date: "2026-09-10", service: "Regular cleaning", price: 80 }],
    notes: "Commercial — cleaned after business hours only, after 18:00.",
    customFields: [
      { label: "Address", value: "Kantstraße 88, 10627 Berlin" },
      { label: "Property size", value: "210 m²" },
      { label: "Rooms", value: "6 (open-plan office)" },
      { label: "Access instructions", value: "Front desk holds a spare key, sign in with reception." },
    ],
  },
  {
    id: "property-schmidt-house",
    name: "Schmidt Family House",
    email: "j.schmidt@example.com",
    phone: "+49 160 1122 3344",
    tags: ["new"],
    lastVisit: null,
    upcoming: [{ date: "2026-09-22", time: "10:30", service: "Windows" }],
    history: [],
    notes: "First-time client, requested a walkthrough before starting.",
    customFields: [
      { label: "Address", value: "Birkenweg 3, 14167 Berlin" },
      { label: "Property size", value: "140 m²" },
      { label: "Rooms", value: "5" },
      { label: "Access instructions", value: "Someone is usually home — ring the bell." },
    ],
  },
];

const appointments: Appointment[] = [
  {
    id: "cl-1",
    client: "Schmidt Family House",
    service: "Windows",
    staff: "Julia",
    resourceId: null,
    date: "2026-09-22",
    time: "10:30",
    durationMinutes: 60,
    price: 50,
    currency: "EUR",
    notes: "",
    visibility: "normal",
    financialBucket: "main",
    status: "pending",
    paid: false,
    seriesId: null,
    recurrence: null,
  },
  {
    id: "cl-2",
    client: "Fischer Residence",
    service: "Deep cleaning",
    staff: "Tom",
    resourceId: "res-vacuum",
    date: "2026-09-22",
    time: "16:00",
    durationMinutes: 180,
    price: 180,
    currency: "EUR",
    notes: "Dog on premises — leave back door closed.",
    visibility: "normal",
    financialBucket: "main",
    status: "confirmed",
    paid: false,
    seriesId: null,
    recurrence: null,
  },
  {
    id: "cl-3",
    client: "Weber & Co. Office",
    service: "Regular cleaning",
    staff: "You",
    resourceId: null,
    date: "2026-09-23",
    time: "18:30",
    durationMinutes: 90,
    price: 80,
    currency: "EUR",
    notes: "After business hours only.",
    visibility: "normal",
    financialBucket: "main",
    status: "confirmed",
    paid: true,
    seriesId: null,
    recurrence: null,
  },
];

/** Cleaning — property-based service business; resources are equipment
 * and the service vehicle, not rooms (properties are the clients). */
export const cleaningWorkspace: WorkspaceConfig = {
  slug: "demo-cleaning",
  industry: "cleaning",
  name: "Cleaning Service",
  tagline: "Regular cleaning, deep cleaning, windows",
  emoji: "🧽",
  clientDescription: {
    de: "Reinigung von Haus und Räumlichkeiten",
    en: "Home and premises cleaning",
    uk: "Прибирання дому та приміщень",
    ru: "Уборка дома и помещений",
  },
  clientLabel: "Property",
  clientLabelPlural: "Properties",
  staffLabel: { de: "Mitarbeiter", en: "Staff member", uk: "Працівник", ru: "Сотрудник" },
  resourceLabel: {
    de: "Fahrzeug / Ausrüstung",
    en: "Vehicle / equipment",
    uk: "Автомобіль / обладнання",
    ru: "Автомобиль / оборудование",
  },
  noResourceLabel: {
    de: "Kein Fahrzeug/Ausrüstung nötig",
    en: "No vehicle/equipment needed",
    uk: "Без автомобіля/обладнання",
    ru: "Без автомобиля/оборудования",
  },
  workLabel: { de: "Aufträge", en: "Jobs", uk: "Замовлення", ru: "Заказы" },
  workIntro: {
    de: "Verwalten Sie Kundenanfragen und Aufträge von der ersten Anfrage bis zur Bezahlung.",
    en: "Manage customer requests and jobs from first contact through to payment.",
    uk: "Керуйте запитами та замовленнями на послуги від звернення клієнта до оплати.",
    ru: "Управляйте запросами и заказами на услуги от обращения клиента до оплаты.",
  },
  financeIntro: {
    de: "Rechnungen, Zahlungen und Umsatz Ihres Unternehmens.",
    en: "Invoices, payments and revenue for your business.",
    uk: "Рахунки, оплати та дохід вашого бізнесу.",
    ru: "Счета, оплаты и выручка вашего бизнеса.",
  },
  analyticsIntro: {
    de: "Wichtige Kennzahlen auf Basis von Terminen, Aufträgen, Kunden und Finanzen.",
    en: "Key business metrics based on appointments, jobs, clients and finance.",
    uk: "Ключові показники бізнесу на основі записів, замовлень, клієнтів та фінансів.",
    ru: "Ключевые показатели бизнеса на основе записей, заказов, клиентов и финансов.",
  },
  services,
  staff,
  resources,
  clients,
  appointments,
};
