import type { WorkspaceConfig } from "../types";
import type { ServiceDefinition } from "@/features/services/types";
import type { StaffMember } from "@/features/staff/types";
import type { ClientRecord } from "@/features/clients/types";
import type { Appointment } from "@/features/appointments/types";

const services: ServiceDefinition[] = [
  {
    id: "svc-regular-cleaning",
    name: "Regular cleaning",
    durationMinutes: 90,
    price: 80,
    currency: "EUR",
    bufferBeforeMinutes: 0,
    bufferAfterMinutes: 15,
    allowedStaffIds: [],
    requiredResourceType: null,
  },
  {
    id: "svc-deep-cleaning",
    name: "Deep cleaning",
    durationMinutes: 180,
    price: 180,
    currency: "EUR",
    bufferBeforeMinutes: 0,
    bufferAfterMinutes: 30,
    allowedStaffIds: [],
    requiredResourceType: null,
  },
  {
    id: "svc-windows",
    name: "Windows",
    durationMinutes: 60,
    price: 50,
    currency: "EUR",
    bufferBeforeMinutes: 0,
    bufferAfterMinutes: 10,
    allowedStaffIds: [],
    requiredResourceType: null,
  },
];

const staff: StaffMember[] = [
  { id: "staff-julia", name: "Julia", colorToken: "--color-accent-mint" },
  { id: "staff-tom", name: "Tom", colorToken: "--color-accent-blue" },
  { id: "staff-you", name: "You", colorToken: "--color-accent-lavender" },
];

const clients: ClientRecord[] = [
  {
    id: "property-fischer",
    name: "Fischer Residence",
    email: "laura.fischer@example.com",
    phone: "+49 176 9988 7766",
    tags: ["vip"],
    lastVisit: "2026-09-15",
    upcoming: [{ date: "2026-09-22", time: "16:00", service: "Deep cleaning" }],
    history: [
      { date: "2026-09-15", service: "Regular cleaning", price: 80 },
      { date: "2026-09-01", service: "Regular cleaning", price: 80 },
    ],
    notes: "Has a dog — leave the back door closed.",
    customFields: [
      { label: "Address", value: "Lindenstraße 14, 10969 Berlin" },
      { label: "Property size", value: "95 m²" },
      { label: "Rooms", value: "4" },
      { label: "Access instructions", value: "Key box code 4471. Dog on premises, no need to let out." },
    ],
  },
  {
    id: "property-weber-office",
    name: "Weber & Co. Office",
    email: "office@weberco.example",
    phone: "+49 30 4455 6677",
    tags: [],
    lastVisit: "2026-09-10",
    upcoming: [],
    history: [{ date: "2026-09-10", service: "Regular cleaning", price: 80 }],
    notes: "Commercial — cleaned after business hours only, after 18:00.",
    customFields: [
      { label: "Address", value: "Kantstraße 88, 10627 Berlin" },
      { label: "Property size", value: "210 m²" },
      { label: "Rooms", value: "6 (open-plan office)" },
      { label: "Access instructions", value: "Front desk holds a spare key, sign in with reception." },
    ],
  },
  {
    id: "property-schmidt-house",
    name: "Schmidt Family House",
    email: "j.schmidt@example.com",
    phone: "+49 160 1122 3344",
    tags: ["new"],
    lastVisit: null,
    upcoming: [{ date: "2026-09-22", time: "10:30", service: "Windows" }],
    history: [],
    notes: "First-time client, requested a walkthrough before starting.",
    customFields: [
      { label: "Address", value: "Birkenweg 3, 14167 Berlin" },
      { label: "Property size", value: "140 m²" },
      { label: "Rooms", value: "5" },
      { label: "Access instructions", value: "Someone is usually home — ring the bell." },
    ],
  },
];

const appointments: Appointment[] = [
  {
    id: "cl-1",
    client: "Schmidt Family House",
    service: "Windows",
    staff: "Julia",
    resourceId: null,
    date: "2026-09-22",
    time: "10:30",
    durationMinutes: 60,
    price: 50,
    currency: "EUR",
    notes: "",
    visibility: "normal",
    financialBucket: "main",
    status: "pending",
    paid: false,
    seriesId: null,
    recurrence: null,
  },
  {
    id: "cl-2",
    client: "Fischer Residence",
    service: "Deep cleaning",
    staff: "Tom",
    resourceId: null,
    date: "2026-09-22",
    time: "16:00",
    durationMinutes: 180,
    price: 180,
    currency: "EUR",
    notes: "Dog on premises — leave back door closed.",
    visibility: "normal",
    financialBucket: "main",
    status: "confirmed",
    paid: false,
    seriesId: null,
    recurrence: null,
  },
  {
    id: "cl-3",
    client: "Weber & Co. Office",
    service: "Regular cleaning",
    staff: "You",
    resourceId: null,
    date: "2026-09-23",
    time: "18:30",
    durationMinutes: 90,
    price: 80,
    currency: "EUR",
    notes: "After business hours only.",
    visibility: "normal",
    financialBucket: "main",
    status: "confirmed",
    paid: true,
    seriesId: null,
    recurrence: null,
  },
];

/** Cleaning — property-based service business, no vehicles/rooms needed. */
export const cleaningWorkspace: WorkspaceConfig = {
  slug: "demo-cleaning",
  industry: "cleaning",
  name: "Cleaning Service",
  tagline: "Regular cleaning, deep cleaning, windows",
  emoji: "🧽",
  clientLabel: "Property",
  clientLabelPlural: "Properties",
  services,
  staff,
  resources: [],
  clients,
  appointments,
};
