import type { WorkspaceConfig } from "../types";
import type { ServiceDefinition } from "@/features/services/types";
import type { StaffMember } from "@/features/staff/types";
import type { ResourceDefinition } from "@/features/resources/types";
import type { ClientRecord } from "@/features/clients/types";
import type { Appointment } from "@/features/appointments/types";

const services: ServiceDefinition[] = [
  {
    id: "svc-oelwechsel",
    name: "Ölwechsel",
    durationMinutes: 30,
    price: 60,
    currency: "EUR",
    bufferBeforeMinutes: 0,
    bufferAfterMinutes: 10,
    allowedStaffIds: [],
    requiredResourceType: "equipment",
  },
  {
    id: "svc-reifenwechsel",
    name: "Reifenwechsel",
    durationMinutes: 40,
    price: 50,
    currency: "EUR",
    bufferBeforeMinutes: 0,
    bufferAfterMinutes: 10,
    allowedStaffIds: [],
    requiredResourceType: "equipment",
  },
  {
    id: "svc-inspektion",
    name: "Inspektion",
    durationMinutes: 90,
    price: 150,
    currency: "EUR",
    bufferBeforeMinutes: 0,
    bufferAfterMinutes: 15,
    allowedStaffIds: ["staff-marco"],
    requiredResourceType: "equipment",
  },
  {
    id: "svc-bremsen",
    name: "Bremsen",
    durationMinutes: 75,
    price: 180,
    currency: "EUR",
    bufferBeforeMinutes: 0,
    bufferAfterMinutes: 15,
    allowedStaffIds: [],
    requiredResourceType: "equipment",
  },
  {
    id: "svc-diagnose",
    name: "Diagnose",
    durationMinutes: 45,
    price: 70,
    currency: "EUR",
    bufferBeforeMinutes: 0,
    bufferAfterMinutes: 5,
    allowedStaffIds: [],
    requiredResourceType: null,
  },
];

const staff: StaffMember[] = [
  { id: "staff-marco", name: "Marco", colorToken: "--color-accent-peach" },
  { id: "staff-sven", name: "Sven", colorToken: "--color-accent-blue" },
  { id: "staff-you", name: "You", colorToken: "--color-accent-lavender" },
];

const resources: ResourceDefinition[] = [
  { id: "res-lift-1", name: "Hebebühne 1", type: "equipment" },
  { id: "res-lift-2", name: "Hebebühne 2", type: "equipment" },
];

const clients: ClientRecord[] = [
  {
    id: "vehicle-bmw-x5",
    name: "BMW X5",
    email: "k.hoffmann@example.com",
    phone: "+49 171 2233 4455",
    tags: ["vip"],
    lastVisit: "2026-09-01",
    upcoming: [{ date: "2026-09-22", time: "09:00", service: "Ölwechsel" }],
    history: [
      { date: "2026-09-01", service: "Inspektion", price: 150 },
      { date: "2026-06-14", service: "Bremsen", price: 180 },
    ],
    notes: "Halter: Katrin Hoffmann. Bevorzugt Termine am Vormittag.",
    customFields: [
      { label: "Fahrzeug", value: "BMW X5" },
      { label: "Fahrzeugmodell", value: "BMW X5 xDrive30d (2021)" },
      { label: "Kennzeichen", value: "B-MW 1234" },
      { label: "VIN", value: "WBAJA9C50ME123456" },
      { label: "Kilometerstand", value: "48.500 km" },
    ],
  },
  {
    id: "vehicle-vw-golf",
    name: "VW Golf",
    email: "p.wagner@example.com",
    phone: "+49 160 9988 1122",
    tags: ["new"],
    lastVisit: null,
    upcoming: [{ date: "2026-09-22", time: "10:30", service: "Diagnose" }],
    history: [],
    notes: "Halter: Peter Wagner. Motorwarnleuchte an.",
    customFields: [
      { label: "Fahrzeug", value: "VW Golf" },
      { label: "Fahrzeugmodell", value: "VW Golf 8 GTI (2023)" },
      { label: "Kennzeichen", value: "B-PW 771" },
      { label: "VIN", value: "WVWZZZAUZPW001234" },
      { label: "Kilometerstand", value: "12.300 km" },
    ],
  },
  {
    id: "vehicle-audi-a4",
    name: "Audi A4",
    email: "s.becker@example.com",
    phone: "+49 152 3344 5566",
    tags: [],
    lastVisit: "2026-08-20",
    upcoming: [],
    history: [{ date: "2026-08-20", service: "Reifenwechsel", price: 50 }],
    notes: "Halterin: Sabine Becker.",
    customFields: [
      { label: "Fahrzeug", value: "Audi A4" },
      { label: "Fahrzeugmodell", value: "Audi A4 Avant 40 TDI (2020)" },
      { label: "Kennzeichen", value: "B-SB 4092" },
      { label: "VIN", value: "WAUZZZ8K9LA123456" },
      { label: "Kilometerstand", value: "76.200 km" },
    ],
  },
  {
    id: "vehicle-mb-sprinter",
    name: "Mercedes Sprinter",
    email: "fuhrpark@logistik-noack.example",
    phone: "+49 30 5544 3322",
    tags: ["vip"],
    lastVisit: "2026-09-10",
    upcoming: [{ date: "2026-09-24", time: "13:30", service: "Bremsen" }],
    history: [{ date: "2026-09-10", service: "Ölwechsel", price: 60 }],
    notes: "Firmenfahrzeug — Logistik Noack GmbH. Flotten-Rahmenvertrag.",
    customFields: [
      { label: "Fahrzeug", value: "Mercedes Sprinter" },
      { label: "Fahrzeugmodell", value: "Mercedes-Benz Sprinter 316 CDI (2019)" },
      { label: "Kennzeichen", value: "B-LN 500" },
      { label: "VIN", value: "WDB9066331S123456" },
      { label: "Kilometerstand", value: "142.800 km" },
    ],
  },
];

const appointments: Appointment[] = [
  {
    id: "wk-1",
    client: "BMW X5",
    service: "Ölwechsel",
    staff: "Marco",
    resourceId: "res-lift-1",
    date: "2026-09-22",
    time: "09:00",
    durationMinutes: 60,
    price: 60,
    currency: "EUR",
    notes: "",
    visibility: "normal",
    financialBucket: "main",
    status: "confirmed",
    paid: true,
    seriesId: null,
    recurrence: null,
  },
  {
    id: "wk-2",
    client: "VW Golf",
    service: "Diagnose",
    staff: "Sven",
    resourceId: null,
    date: "2026-09-22",
    time: "10:30",
    durationMinutes: 45,
    price: 70,
    currency: "EUR",
    notes: "Motorwarnleuchte prüfen.",
    visibility: "normal",
    financialBucket: "main",
    status: "pending",
    paid: false,
    seriesId: null,
    recurrence: null,
  },
  {
    id: "wk-3",
    client: "Audi A4",
    service: "Reifenwechsel",
    staff: "You",
    resourceId: "res-lift-2",
    date: "2026-09-22",
    time: "14:00",
    durationMinutes: 40,
    price: 50,
    currency: "EUR",
    notes: "",
    visibility: "normal",
    financialBucket: "main",
    status: "confirmed",
    paid: false,
    seriesId: null,
    recurrence: null,
  },
  {
    id: "wk-4",
    client: "Mercedes Sprinter",
    service: "Bremsen",
    staff: "Marco",
    resourceId: "res-lift-1",
    date: "2026-09-24",
    time: "13:30",
    durationMinutes: 75,
    price: 180,
    currency: "EUR",
    notes: "",
    visibility: "normal",
    financialBucket: "main",
    status: "confirmed",
    paid: false,
    seriesId: null,
    recurrence: null,
  },
  {
    id: "wk-5",
    client: "BMW X5",
    service: "Inspektion",
    staff: "Marco",
    resourceId: "res-lift-2",
    date: "2026-09-23",
    time: "11:00",
    durationMinutes: 90,
    price: 150,
    currency: "EUR",
    notes: "",
    visibility: "normal",
    financialBucket: "main",
    status: "pending",
    paid: false,
    seriesId: null,
    recurrence: null,
  },
];

/** Werkstatt / Auto Service — the flagship "not just beauty" preset. */
export const werkstattWorkspace: WorkspaceConfig = {
  slug: "demo-werkstatt",
  industry: "werkstatt",
  name: "Auto Service",
  tagline: "Ölwechsel, Reifen, Inspektion, Bremsen, Diagnose",
  emoji: "🔧",
  clientLabel: "Vehicle",
  clientLabelPlural: "Vehicles",
  services,
  staff,
  resources,
  clients,
  appointments,
};
