import type { WorkspaceConfig } from "../types";
import type { ServiceDefinition } from "@/features/services/types";
import type { StaffMember } from "@/features/staff/types";
import type { ResourceDefinition } from "@/features/resources/types";
import type { ClientRecord } from "@/features/clients/types";
import type { Appointment } from "@/features/appointments/types";

const services: ServiceDefinition[] = [
  {
    id: "svc-oelwechsel",
    name: "Ölwechsel",
    translations: { en: "Oil change", de: "Ölwechsel", uk: "Заміна оливи", ru: "Замена масла" },
    durationMinutes: 30,
    price: 60,
    currency: "EUR",
    bufferBeforeMinutes: 0,
    bufferAfterMinutes: 10,
    allowedStaffIds: [],
    requiredResourceType: "lift",
  },
  {
    id: "svc-reifenwechsel",
    name: "Reifenwechsel",
    translations: { en: "Tire change", de: "Reifenwechsel", uk: "Заміна шин", ru: "Замена шин" },
    durationMinutes: 40,
    price: 50,
    currency: "EUR",
    bufferBeforeMinutes: 0,
    bufferAfterMinutes: 10,
    allowedStaffIds: [],
    requiredResourceType: "tire",
  },
  {
    id: "svc-inspektion",
    name: "Inspektion",
    translations: { en: "Inspection", de: "Inspektion", uk: "Технічний огляд", ru: "Техосмотр" },
    durationMinutes: 90,
    price: 150,
    currency: "EUR",
    bufferBeforeMinutes: 0,
    bufferAfterMinutes: 15,
    allowedStaffIds: ["staff-marco"],
    requiredResourceType: "lift",
  },
  {
    id: "svc-bremsen",
    name: "Bremsen",
    translations: { en: "Brakes", de: "Bremsen", uk: "Гальма", ru: "Тормоза" },
    durationMinutes: 75,
    price: 180,
    currency: "EUR",
    bufferBeforeMinutes: 0,
    bufferAfterMinutes: 15,
    allowedStaffIds: [],
    requiredResourceType: "lift",
  },
  {
    id: "svc-diagnose",
    name: "Diagnose",
    translations: { en: "Diagnostics", de: "Diagnose", uk: "Діагностика", ru: "Диагностика" },
    durationMinutes: 45,
    price: 70,
    currency: "EUR",
    bufferBeforeMinutes: 0,
    bufferAfterMinutes: 5,
    allowedStaffIds: [],
    requiredResourceType: "diagnostic",
  },
];

const staff: StaffMember[] = [
  { id: "staff-marco", name: "Marco", colorToken: "--color-accent-peach" },
  { id: "staff-sven", name: "Sven", colorToken: "--color-accent-blue" },
  { id: "staff-you", name: "You", colorToken: "--color-accent-lavender" },
];

const resources: ResourceDefinition[] = [
  {
    id: "res-lift-1",
    name: "Hebebühne 1",
    type: "lift",
    translations: { de: "Hebebühne 1", en: "Lift 1", uk: "Підйомник 1", ru: "Подъёмник 1" },
  },
  {
    id: "res-lift-2",
    name: "Hebebühne 2",
    type: "lift",
    translations: { de: "Hebebühne 2", en: "Lift 2", uk: "Підйомник 2", ru: "Подъёмник 2" },
  },
  {
    id: "res-diagnostic",
    name: "Diagnoseplatz",
    type: "diagnostic",
    translations: {
      de: "Diagnoseplatz",
      en: "Diagnostic bay",
      uk: "Діагностичний пост",
      ru: "Диагностический пост",
    },
  },
  {
    id: "res-tire",
    name: "Reifenservice-Platz",
    type: "tire",
    translations: {
      de: "Reifenservice-Platz",
      en: "Tire service bay",
      uk: "Шиномонтажний пост",
      ru: "Шиномонтажный пост",
    },
  },
];

const clients: ClientRecord[] = [
  {
    id: "vehicle-bmw-x5",
    name: "BMW X5",
    email: "k.hoffmann@example.com",
    phone: "+49 171 2233 4455",
    tags: ["vip"],
    lastVisit: "2026-09-01",
    upcoming: [{ date: "2026-09-22", time: "09:00", service: "Ölwechsel" }],
    history: [
      { date: "2026-09-01", service: "Inspektion", price: 150 },
      { date: "2026-06-14", service: "Bremsen", price: 180 },
    ],
    notes: "Halter: Katrin Hoffmann. Bevorzugt Termine am Vormittag.",
    customFields: [
      { label: "Fahrzeug", value: "BMW X5" },
      { label: "Fahrzeugmodell", value: "BMW X5 xDrive30d (2021)" },
      { label: "Kennzeichen", value: "B-MW 1234" },
      { label: "VIN", value: "WBAJA9C50ME123456" },
      { label: "Kilometerstand", value: "48.500 km" },
    ],
  },
  {
    id: "vehicle-vw-golf",
    name: "VW Golf",
    email: "p.wagner@example.com",
    phone: "+49 160 9988 1122",
    tags: ["new"],
    lastVisit: null,
    upcoming: [{ date: "2026-09-22", time: "10:30", service: "Diagnose" }],
    history: [],
    notes: "Halter: Peter Wagner. Motorwarnleuchte an.",
    customFields: [
      { label: "Fahrzeug", value: "VW Golf" },
      { label: "Fahrzeugmodell", value: "VW Golf 8 GTI (2023)" },
      { label: "Kennzeichen", value: "B-PW 771" },
      { label: "VIN", value: "WVWZZZAUZPW001234" },
      { label: "Kilometerstand", value: "12.300 km" },
    ],
  },
  {
    id: "vehicle-audi-a4",
    name: "Audi A4",
    email: "s.becker@example.com",
    phone: "+49 152 3344 5566",
    tags: [],
    lastVisit: "2026-08-20",
    upcoming: [],
    history: [{ date: "2026-08-20", service: "Reifenwechsel", price: 50 }],
    notes: "Halterin: Sabine Becker.",
    customFields: [
      { label: "Fahrzeug", value: "Audi A4" },
      { label: "Fahrzeugmodell", value: "Audi A4 Avant 40 TDI (2020)" },
      { label: "Kennzeichen", value: "B-SB 4092" },
      { label: "VIN", value: "WAUZZZ8K9LA123456" },
      { label: "Kilometerstand", value: "76.200 km" },
    ],
  },
  {
    id: "vehicle-mb-sprinter",
    name: "Mercedes Sprinter",
    email: "fuhrpark@logistik-noack.example",
    phone: "+49 30 5544 3322",
    tags: ["vip"],
    lastVisit: "2026-09-10",
    upcoming: [{ date: "2026-09-24", time: "13:30", service: "Bremsen" }],
    history: [{ date: "2026-09-10", service: "Ölwechsel", price: 60 }],
    notes: "Firmenfahrzeug — Logistik Noack GmbH. Flotten-Rahmenvertrag.",
    customFields: [
      { label: "Fahrzeug", value: "Mercedes Sprinter" },
      { label: "Fahrzeugmodell", value: "Mercedes-Benz Sprinter 316 CDI (2019)" },
      { label: "Kennzeichen", value: "B-LN 500" },
      { label: "VIN", value: "WDB9066331S123456" },
      { label: "Kilometerstand", value: "142.800 km" },
    ],
  },
];

const appointments: Appointment[] = [
  {
    id: "wk-1",
    client: "BMW X5",
    service: "Ölwechsel",
    staff: "Marco",
    resourceId: "res-lift-1",
    date: "2026-09-22",
    time: "09:00",
    durationMinutes: 60,
    price: 60,
    currency: "EUR",
    notes: "",
    visibility: "normal",
    financialBucket: "main",
    status: "confirmed",
    paid: true,
    seriesId: null,
    recurrence: null,
  },
  {
    id: "wk-2",
    client: "VW Golf",
    service: "Diagnose",
    staff: "Sven",
    resourceId: "res-diagnostic",
    date: "2026-09-22",
    time: "10:30",
    durationMinutes: 45,
    price: 70,
    currency: "EUR",
    notes: "Motorwarnleuchte prüfen.",
    visibility: "normal",
    financialBucket: "main",
    status: "pending",
    paid: false,
    seriesId: null,
    recurrence: null,
  },
  {
    id: "wk-3",
    client: "Audi A4",
    service: "Reifenwechsel",
    staff: "You",
    resourceId: "res-tire",
    date: "2026-09-22",
    time: "14:00",
    durationMinutes: 40,
    price: 50,
    currency: "EUR",
    notes: "",
    visibility: "normal",
    financialBucket: "main",
    status: "confirmed",
    paid: false,
    seriesId: null,
    recurrence: null,
  },
  {
    id: "wk-4",
    client: "Mercedes Sprinter",
    service: "Bremsen",
    staff: "Marco",
    resourceId: "res-lift-1",
    date: "2026-09-24",
    time: "13:30",
    durationMinutes: 75,
    price: 180,
    currency: "EUR",
    notes: "",
    visibility: "normal",
    financialBucket: "main",
    status: "confirmed",
    paid: false,
    seriesId: null,
    recurrence: null,
  },
  {
    id: "wk-5",
    client: "BMW X5",
    service: "Inspektion",
    staff: "Marco",
    resourceId: "res-lift-2",
    date: "2026-09-23",
    time: "11:00",
    durationMinutes: 90,
    price: 150,
    currency: "EUR",
    notes: "",
    visibility: "normal",
    financialBucket: "main",
    status: "pending",
    paid: false,
    seriesId: null,
    recurrence: null,
  },
];

/** Werkstatt / Auto Service — the flagship "not just beauty" preset. */
export const werkstattWorkspace: WorkspaceConfig = {
  slug: "demo-werkstatt",
  industry: "werkstatt",
  name: "Auto Service",
  tagline: "Ölwechsel, Reifen, Inspektion, Bremsen, Diagnose",
  emoji: "🔧",
  clientDescription: {
    de: "Reparatur und Wartung Ihres Fahrzeugs",
    en: "Vehicle repair and maintenance",
    uk: "Ремонт і обслуговування автомобіля",
    ru: "Ремонт и обслуживание автомобиля",
  },
  clientLabel: "Vehicle",
  clientLabelPlural: "Vehicles",
  staffLabel: { de: "Mechaniker", en: "Mechanic", uk: "Механік", ru: "Механик" },
  resourceLabel: {
    de: "Arbeitsplatz / Hebebühne",
    en: "Bay / lift",
    uk: "Пост / підйомник",
    ru: "Пост / подъёмник",
  },
  noResourceLabel: {
    de: "Kein Arbeitsplatz erforderlich",
    en: "No bay required",
    uk: "Без окремого поста",
    ru: "Без отдельного поста",
  },
  workLabel: { de: "Aufträge", en: "Jobs", uk: "Замовлення", ru: "Заказы" },
  workIntro: {
    de: "Verwalten Sie Kundenanfragen, Angebote und Aufträge bis zur Rechnungsstellung.",
    en: "Manage customer requests, quotes and jobs through to invoicing.",
    uk: "Керуйте запитами, пропозиціями та замовленнями клієнтів до виставлення рахунку.",
    ru: "Управляйте запросами, предложениями и заказами клиентов до выставления счёта.",
  },
  financeIntro: {
    de: "Rechnungen, Zahlungen und Umsatz Ihres Unternehmens.",
    en: "Invoices, payments and revenue for your business.",
    uk: "Рахунки, оплати та дохід вашого бізнесу.",
    ru: "Счета, оплаты и выручка вашего бизнеса.",
  },
  analyticsIntro: {
    de: "Wichtige Kennzahlen auf Basis von Terminen, Aufträgen, Kunden und Finanzen.",
    en: "Key business metrics based on appointments, jobs, clients and finance.",
    uk: "Ключові показники бізнесу на основі записів, замовлень, клієнтів та фінансів.",
    ru: "Ключевые показатели бизнеса на основе записей, заказов, клиентов и финансов.",
  },
  services,
  staff,
  resources,
  clients,
  appointments,
};
