import type { ServiceDefinition } from "./types";

export const demoServices: ServiceDefinition[] = [
  {
    id: "svc-haircut",
    name: "Haircut",
    durationMinutes: 45,
    price: 55,
    currency: "EUR",
    bufferBeforeMinutes: 0,
    bufferAfterMinutes: 10,
    allowedStaffIds: ["staff-elena"],
    requiredResourceType: null,
  },
  {
    id: "svc-consultation",
    name: "Consultation",
    durationMinutes: 30,
    price: 40,
    currency: "EUR",
    bufferBeforeMinutes: 0,
    bufferAfterMinutes: 5,
    allowedStaffIds: [],
    requiredResourceType: null,
  },
  {
    id: "svc-deep-cleaning",
    name: "Deep cleaning",
    durationMinutes: 90,
    price: 120,
    currency: "EUR",
    bufferBeforeMinutes: 0,
    bufferAfterMinutes: 15,
    allowedStaffIds: ["staff-marco"],
    requiredResourceType: "vehicle",
  },
  {
    id: "svc-website-maintenance",
    name: "Website maintenance",
    durationMinutes: 60,
    price: 180,
    currency: "EUR",
    bufferBeforeMinutes: 0,
    bufferAfterMinutes: 0,
    allowedStaffIds: [],
    requiredResourceType: null,
  },
  {
    id: "svc-color",
    name: "Color",
    durationMinutes: 90,
    price: 95,
    currency: "EUR",
    bufferBeforeMinutes: 0,
    bufferAfterMinutes: 15,
    allowedStaffIds: ["staff-elena"],
    requiredResourceType: "room",
  },
];
